pack: rebuild update.img with QuickJS MINI (not FULL)
QuickJS FULL is unbuildable on NuttX - quickjs-libc.c assumes Linux
libc and pulls in popen/pclose/pipe/symlink/readlink, none of which
exist in NuttX.  Tested:

  ninja: build stopped: subcommand failed.
  quickjs-libc.c:801: undefined reference to pclose
  quickjs-libc.c:3068: undefined reference to pipe
  quickjs-libc.c:1045: undefined reference to pclose
  quickjs-libc.c:2690: undefined reference to symlink
  ... (and more)

QuickJS MINI = the qjsmini.c REPL that only supports console.log -
compiles cleanly and links into nuttx (no quickjs-libc.c).

Side note: the NSH command is 'qjs' (not 'qjsmini' as I confused
it with the source file name).  See the QUICKJS_MINI branch of
apps/interpreters/quickjs/CMakeLists.txt:

  nuttx_add_application(NAME qjs ... SRCS qjsmini.c ...)

So to invoke it:

  nsh> qjs
  > console.log('Hello, World!!')
  Hello, World!!
  >

This commit rebuilds the rockdev image with the same MINI build
as the previous pack commit.  Just verifies the link is good and
re-stamps the artifact timestamps.